DROP TRIGGER IF EXISTS checkin_count_sync ON check_ins;
DROP TRIGGER IF EXISTS users_updated_at ON users;
DROP FUNCTION IF EXISTS sync_checkin_count();
DROP FUNCTION IF EXISTS update_updated_at();
DROP TABLE IF EXISTS spam_flags;
DROP TABLE IF EXISTS reactions;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS check_ins;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS invites;
DROP TABLE IF EXISTS webauthn_credentials;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS drink_requests;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS drinks;
DROP TYPE IF EXISTS checkin_status;
DROP TYPE IF EXISTS reaction_type;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS drink_request_status;
